---
title: "Introduction to splines2"
author: Wenjie Wang
date: "`r Sys.Date()`"
bibliography:
- ../inst/bib/splines2.bib
vignette: >
  %\VignetteIndexEntry{Introduction to splines2}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
output: rmarkdown::html_vignette
---

```{r setup, echo = FALSE, message = FALSE}
library(splines, quietly = TRUE)
source("../R/intBs.R")
source("../R/mSpline.R")
source("../R/iSpline.R")
```

## Examples of Integral B-splines

Formula from @de1978practical.

```{r intBs1, fig.width=7, fig.height=4}
x <- seq(0, 1, by = .01)
knots <- c(0.2, 0.4, 0.7, 0.9)
ibsOut <- ibs(x, knots = knots, degree = 1, intercept = TRUE)
par(mar = c(2.5, 2.5, 0, 0), mgp = c(1.5, 0.5, 0))
matplot(x, ibsOut$bsMat, type = "l", ylab = "B-spline bases")
abline(v = knots, lty = 2, col = "gray")
matplot(x, ibsOut$ibsMat, type = "l", ylab = "Integral of B-spline bases")
abline(v = knots, lty = 2, col = "gray")
```

## Example of M-splines

Example from @ramsay1988monotone.

```{r mSpline, fig.width=7, fig.height=4}
knots <- c(0.3, 0.5, 0.6)
imsOut <- ims(x, knots = knots, degree = 2, intercept = TRUE)
par(mar = c(2.5, 2.5, 0, 0), mgp = c(1.5, 0.5, 0))
matplot(x, imsOut$msMat, type = "l", ylab = "M-spline bases")
abline(v = knots, lty = 2, col = "gray")
matplot(x, imsOut$imsMat, type = "l", ylab = "I-spline bases")
abline(v = knots, lty = 2, col = "gray")
```

## Reference

